"""Ids start from 101 (3)

Revision ID: 0d30ce8525c2
Revises: 2756aef0e820
Create Date: 2025-01-21 14:28:53.146535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d30ce8525c2'
down_revision: Union[str, None] = '2756aef0e820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
