"""Ids start from 101

Revision ID: 2756aef0e820
Revises: 7ab9fd0ed0c6
Create Date: 2025-01-21 14:27:04.513492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2756aef0e820'
down_revision: Union[str, None] = '7ab9fd0ed0c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
