"""feat: Author id starts with 101

Revision ID: 59f3b9dd125a
Revises: 0ecf78be0148
Create Date: 2025-01-21 13:03:56.627143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59f3b9dd125a'
down_revision: Union[str, None] = '0ecf78be0148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
