"""Lending

Revision ID: c58303c6d7c8
Revises: 8ca607a2c12f
Create Date: 2025-01-16 18:11:49.898366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c58303c6d7c8'
down_revision: Union[str, None] = '8ca607a2c12f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lendings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lend_time', sa.Date(), nullable=False),
    sa.Column('return_time', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lendings')
    # ### end Alembic commands ###
